/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2024-07-26 14:08:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/VISION%20HOLDING/Desktop/PJ_FACTURE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/RECOUVREMENT/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/sql-1_1.tld", Long.valueOf(1664453478000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1721664336439L));
    _jspx_dependants.put("jar:file:/C:/Users/VISION%20HOLDING/Desktop/PJ_FACTURE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/RECOUVREMENT/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664453478000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("	<title>Page de Connexion</title><meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"/>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("	<style type=\"text/css\">\r\n");
      out.write("	@import url(assets/css/css.css);\r\n");
      out.write("		html,body,div,h1{\r\n");
      out.write("			border: 0;\r\n");
      out.write("			font: inherit;\r\n");
      out.write("			font-size: 100%;\r\n");
      out.write("			margin: 0;padding: 0;\r\n");
      out.write("			vertical-align: baseline;\r\n");
      out.write("			text-rendering: optimizeLegibility;\r\n");
      out.write("		}\r\n");
      out.write("		html,body{\r\n");
      out.write("			heigth: 100%;\r\n");
      out.write("			margin: 0;padding: 0;\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		body{\r\n");
      out.write("			background:  url('assets/facture.jpg') no-repeat fixed;\r\n");
      out.write("			background-size: cover;\r\n");
      out.write("			color: #FFF;\r\n");
      out.write("			font-family: \"Helvetica Neue Light\", \"Helvetica Neue\", Helvetica, Arial, \"Lucida Grande\", sans-serif;\r\n");
      out.write("			font-size: 12px;\r\n");
      out.write("			line-heght: 1;\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		.background-wrap {\r\n");
      out.write("			width : 100%;\r\n");
      out.write("			height: 50%;\r\n");
      out.write("			position: absolute;\r\n");
      out.write("			top: 0;left:0;\r\n");
      out.write("			z-index: -1;\r\n");
      out.write("			overflow: hidden;\r\n");
      out.write("		}\r\n");
      out.write("		.background{\r\n");
      out.write("			background:;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		*{\r\n");
      out.write("			box-sizing: border-box;\r\n");
      out.write("			cursor: default;outline:none;\r\n");
      out.write("		}\r\n");
      out.write("		form {\r\n");
      out.write("			background: rgba(0, 0, 0, 0.5);border: 1px solid #191919;border-radius: .4em;bottom: 0;\r\n");
      out.write("			box-shadow: 0 5px 10px 5px rgb(0,0,0,0.2);height: 450px; left: 0;margin: auto;overflow: hidden;\r\n");
      out.write("			position: absolute; right:0%;top: 20%;width: 350px; margin-top: 150px;\r\n");
      out.write("		\r\n");
      out.write("		}\r\n");
      out.write("		form:after {\r\n");
      out.write("		  background: -webkit-gradient(linear, left top, right top, from(#111111), color-stop(#444444),\r\n");
      out.write("		   color-stop(#b6b6b8), color-stop(#444444), color-stop(#2F2F2F), to(#272727));\r\n");
      out.write("		  background: linear-gradient(to right, #111111, #444444, #b6b6b8, #444444, #2F2F2F, #272727);\r\n");
      out.write("		  content: \"\";\r\n");
      out.write("		  display: inline;\r\n");
      out.write("		  height: 1px;\r\n");
      out.write("		  left: 50px;\r\n");
      out.write("		  position: absolute;\r\n");
      out.write("		  top: 0;\r\n");
      out.write("		  width: 150px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		form:before {\r\n");
      out.write("		  border-radius: 50%;\r\n");
      out.write("		  box-shadow: 0 0 6px 4px #fff;\r\n");
      out.write("		  content: \"\";\r\n");
      out.write("		  display: block;\r\n");
      out.write("		  height: 5px;\r\n");
      out.write("		  left: 34%;\r\n");
      out.write("		  position: absolute;\r\n");
      out.write("		  top: -7px;\r\n");
      out.write("		  width: 8px;\r\n");
      out.write("		}\r\n");
      out.write("		.inset {\r\n");
      out.write("			border-top: 1px solid #19191a;padding: 20px;\r\n");
      out.write("		}\r\n");
      out.write("		form h1 {\r\n");
      out.write("			font-family: 'Audiowide';border-bottom: 1px solid #000;\r\n");
      out.write("			font-size: 18px;padding: 15px 0;position: relative;text-align: center;text-shadow: 0 1px 0 #000;\r\n");
      out.write("			color: #FFbb00;font-weight: normal;\r\n");
      out.write("		}\r\n");
      out.write("		form h1.poweron {\r\n");
      out.write("		  color: #ffffff;\r\n");
      out.write("		  -webkit-transition: all 0.5s;\r\n");
      out.write("		  transition: all 0.5s;\r\n");
      out.write("		  -webkit-animation: flicker 1s ease-in-out 1 alternate, neon 1.5s ease-in-out infinite alternate;\r\n");
      out.write("		          animation: flicker 1s ease-in-out 1 alternate, neon 1.5s ease-in-out infinite alternate;\r\n");
      out.write("		  -webkit-animation-delay: 0s, 1s;\r\n");
      out.write("		          animation-delay: 0s, 1s;\r\n");
      out.write("		}\r\n");
      out.write("		form h1:after {\r\n");
      out.write("		  position: absolute;\r\n");
      out.write("		  width: 250px;\r\n");
      out.write("		  height: 180px;\r\n");
      out.write("		  content: \"\";\r\n");
      out.write("		  display: block;\r\n");
      out.write("		  pointer-events: none;\r\n");
      out.write("		  top: 0;\r\n");
      out.write("		  margin-left: 138px;\r\n");
      out.write("		  -webkit-transform-style: flat;\r\n");
      out.write("		          transform-style: flat;\r\n");
      out.write("		  -webkit-transform: skew(20deg);\r\n");
      out.write("		          transform: skew(20deg);\r\n");
      out.write("		  background: -ms-linear-gradient(top, hsla(0,0%,100%,0.1) 0%,hsla(0,0%,100%,0) 100%);\r\n");
      out.write("		  filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#42ffffff', endColorstr='#00ffffff',\r\n");
      out.write("		  GradientType=0 );\r\n");
      out.write("		  background: -webkit-gradient(linear, left top, left bottom, from(hsla(0,0%,100%,0.1)),to(hsla(0,0%,100%,0)));\r\n");
      out.write("		  background: linear-gradient(to bottom, hsla(0,0%,100%,0.1) 0%,hsla(0,0%,100%,0) 100%);\r\n");
      out.write("		\r\n");
      out.write("		}\r\n");
      out.write("		input[type=email], input[type=password] {\r\n");
      out.write("		  background: -webkit-gradient(linear,left top, left bottom,from(#1f2124),to(#27292c));\r\n");
      out.write("		  background: linear-gradient(#1f2124,#27292c);\r\n");
      out.write("		  border: 1px solid #222;\r\n");
      out.write("		  border-radius: .3em;\r\n");
      out.write("		  box-shadow: 0 1px 0 rgba(255,255,255,0.1);\r\n");
      out.write("		  color: #FFF;\r\n");
      out.write("		  font-size: 13px;\r\n");
      out.write("		  margin-bottom: 20px;\r\n");
      out.write("		  padding: 8px 5px;\r\n");
      out.write("		  width: 100%;\r\n");
      out.write("		} \r\n");
      out.write("		input[type=email]:disabled, input[type=password]:disabled {\r\n");
      out.write("			color: #999;\r\n");
      out.write("		}\r\n");
      out.write("		button[type=submit] {\r\n");
      out.write("		  background: #fb0;\r\n");
      out.write("		  border: 1px solid rgba(0,0,0,0.4);\r\n");
      out.write("		  border-radius: .3em;\r\n");
      out.write("		  box-shadow: inset 0 1px 0 rgba(255,255,255,0.3), inset 0 10px 10px rgba(255,255,255,0.1);\r\n");
      out.write("		  color: #873C00;\r\n");
      out.write("		  cursor: pointer;\r\n");
      out.write("		  font-size: 15px;\r\n");
      out.write("		  font-weight: bold;\r\n");
      out.write("		  height: 40px;\r\n");
      out.write("		  padding: 5px 20px;\r\n");
      out.write("		  width: 100%;\r\n");
      out.write("		  margin-bottom:35px ;\r\n");
      out.write("		}\r\n");
      out.write("		button[type=submit]:hover, button[type=submit]:focus {\r\n");
      out.write("		  box-shadow: inset 0 1px 0 rgba(255,255,255,0.3), inset 0 -10px 10px rgba(255,255,255,0.1);\r\n");
      out.write("		}\r\n");
      out.write("		input[type=email]:hover:not([disabled]), \r\n");
      out.write("		input[type=email]:focus, \r\n");
      out.write("		input[type=password]:hover:not([disabled]), \r\n");
      out.write("		input[type=password]:focus, \r\n");
      out.write("		label:hover ~ input[type=email], \r\n");
      out.write("		label:hover ~ input[type=password] {\r\n");
      out.write("		  background: #27292c;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		a{   \r\n");
      out.write("			color:yellow;\r\n");
      out.write("			text-decoration:none;\r\n");
      out.write("			font-size: 18px;\r\n");
      out.write("			margin-left:5rem\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		div.lien{\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"background-wrap\">\r\n");
      out.write("		<div class=\"background\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<form id=\"access\" action=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" method=\"post\">\r\n");
      out.write("		<h1 id=\"header\" class=\"poweron\">CONNEXION</h1>\r\n");
      out.write("		<div class=\"inset\">\r\n");
      out.write("			<p>\r\n");
      out.write("				<input type=\"email\" name=\"username\" id=\"email\" required placeholder=\"Nom utilisateur\">\r\n");
      out.write("			</p>\r\n");
      out.write("			\r\n");
      out.write("			<p>\r\n");
      out.write("				<input type=\"password\" name=\"password\" id=\"password\" required placeholder=\"Mot de passe\">\r\n");
      out.write("			</p>\r\n");
      out.write("			\r\n");
      out.write("			<hr>\r\n");
      out.write("			\r\n");
      out.write("			<button type=\"submit\" name=\"connexionName\" value=\"connexion\">CONNEXION</button>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"lien\" style=\"height:auto;width:100%;margin-bottom:2rem;display:flex\">\r\n");
      out.write("				 <a class=\"link\" href=\"forgot-password.jsp\">MOT DE PASSE OUBLIE ?</a>\r\n");
      out.write("			\r\n");
      out.write("			</div>\r\n");
      out.write("			   \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <button type=\"submit\" name=\"inscription\" value=\"inscrire\">S'INSCRIRE</button>\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /index.jsp(9,46) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("assets/css/bootstrap.min.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /index.jsp(10,30) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/assets/css/solid.min.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /index.jsp(179,27) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/Login");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }
}
